name: nflex
description: A Flex implementation similar to FlutterFlex, aimed to be simpler, faster, and fixing some limitations. 
version: 0.0.2
repository: https://github.com/BrianCraig/nflex

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0